pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('Desktop/DevOps/week5/calculator') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

    }

    post {
        success {
            echo 'Build successful'
            archiveArtifacts artifacts: 'Desktop/DevOps/week5/calculator/target/*.jar', fingerprint: true
        }
        failure {
            echo 'Build failed'
        }
    }
}
